#!/usr/bin/env bash

my_dir="$(dirname "${BASH_SOURCE[0]}")"
source "$my_dir/_env"

qemu_repo=multiarch/qemu-user-static
latest_tag=$(github_repo_latest_tag $qemu_repo)
url="https://github.com/$qemu_repo/releases/download"

for target in ${targets[*]}; do
    if [[ ! ($target == "x86_64") ]]; then
        curl -Ls "$url/$latest_tag/x86_64_qemu-$(qemu_static_arch $target)-static.tar.gz" | tar xzv
    fi
done
