#!/bin/bash

my_dir="$(dirname "${BASH_SOURCE[0]}")"
source "$my_dir/_env"

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/latest/download/manifest-tool-linux-amd64
chmod +x manifest-tool

cp multi-arch-manifest.template multi-arch-manifest.yaml
sed -i -- "s%__IMAGE_NAME__%$DOCKER_REPO:$DOCKER_TAG%g" multi-arch-manifest.yaml

./manifest-tool push from-spec multi-arch-manifest.yaml
