#!/bin/bash

my_dir="$(dirname "${BASH_SOURCE[0]}")"
source "$my_dir/_env"

qemu_repo=multiarch/qemu-user-static

for target in ${targets[*]}; do
    if [[ ! ($target == "x86_64") ]]; then
        curl -Ls $(github_repo_latest_url $qemu_repo)/x86_64_qemu-$(qemu_static_arch $target)-static.tar.gz | tar xzv
    fi
done
