#!/usr/bin/with-contenv bash

cron_dir="/var/spool/cron/crontabs"
cron_file="$cron_dir/root"

rm -f $cron_file
touch $cron_file

if [[ "${BACKUP_CRON}" ]]; then
    echo "$BACKUP_CRON /app/backup.sh" >> $cron_file
fi

if [[ "${PRUNE_CRON}" ]]; then
    echo "$PRUNE_CRON /app/prune.sh" >> $cron_file
fi

if [[ "${BACKUP_END_CRON}" ]]; then
    echo "$BACKUP_END_CRON /app/end_backup.sh" >> $cron_file
fi

exit 0
